MERGE INTO MUSIC_GENRES.ANALYTICS.ARTIST_EMBEDDINGS ae
USING (
    SELECT
        ac.ARTIST_NAME,
        ac.BIO_SUMMARY,
        SHA2(ac.BIO_SUMMARY) AS BIO_HASH,
        ac.RUN_ID
    FROM MUSIC_GENRES.ANALYTICS.ARTISTS_CLEAN ac
    WHERE ac.BIO_SUMMARY IS NOT NULL
      AND TRIM(ac.BIO_SUMMARY) != ''
) ac
ON ae.ARTIST_NAME = ac.ARTIST_NAME
WHEN MATCHED AND ae.BIO_HASH != ac.BIO_HASH THEN
    UPDATE SET
        BIO_EMBEDDING = SNOWFLAKE.CORTEX.EMBED_TEXT_768('snowflake-arctic-embed-m', ac.BIO_SUMMARY),
        BIO_HASH      = ac.BIO_HASH,
        EMBEDDED_AT   = CURRENT_TIMESTAMP(),
        SOURCE_RUN_ID = ac.RUN_ID
WHEN NOT MATCHED THEN
    INSERT (ARTIST_NAME, BIO_EMBEDDING, BIO_HASH, EMBEDDED_AT, SOURCE_RUN_ID)
    VALUES (
        ac.ARTIST_NAME,
        SNOWFLAKE.CORTEX.EMBED_TEXT_768('snowflake-arctic-embed-m', ac.BIO_SUMMARY),
        ac.BIO_HASH,
        CURRENT_TIMESTAMP(),
        ac.RUN_ID
    );